# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michał Z.
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com
  
# Your disqus shortname, entering this will enable commenting on posts
disqus: mzgreen

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
