# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michał Z.
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         5
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com
  
# Your disqus shortname, entering this will enable commenting on posts
disqus: mzgreen

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
pages_list:       
  Archive: '/archive'
  Feed: '/atom.xml'
  
# Includes an icon in the footer for each username you enter
footer-links:
dribbble:
email:
facebook: 
flickr: 
github: mzgreen
instagram: 
linkedin: frogermcs
pinterest:
rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
twitter: mzmzgreen
stackoverflow:  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
